### ISSUE TITLE
[Feature Request] Updating the `Detect Changes` without having to trigger a the pipeline?

### ISSUE THREAD

**Issue by maxeber** [yet-another-tool/1b2i1c#14]
@studiowebux Would it be possible to allow updating the **changes detection** without having to trigger a the pipeline? Not sure if this is a priority but could offer a better UX and less unnecessary processing on our pipeline?

![image](https://user-images.githubusercontent.com/16073961/211351659-5d1e5b6d-ac08-43df-81f0-76a9c58d8bc2.png)

I would the the flow like
- pick pipeline
- enter branch name
- click "refresh" to get the **AWS CodePipeline Status**
- then you see the **Detect Changes:  {toggle button}** somewhere

_Originally posted by @maxeber in https://github.com/yet-another-tool/1b2i1c/issues/8#issuecomment-1375856311_

**Comment by studiowebux** [comment]
Thanks for your suggestion, I've prepared this PR : https://github.com/yet-another-tool/1b2i1c/pull/15

Let me know if it is good for you !

**Comment by maxeber** [comment]
Works out perfectly! thanks
