### ISSUE TITLE
[Feature Request] Is it possible to display the current deployed branch/commit?

### ISSUE THREAD

**Issue by maxeber** [yet-another-tool/1b2i1c#7]
If possible, I think it would be useful to see what is the current branch that the pipeline targets.
We could maybe see the commit SHA has well?

![image](https://user-images.githubusercontent.com/16073961/210818251-91f5101f-663c-42fe-a114-be3f6918e40d.png)

**Comment by maxeber** [comment]
Oh that was fast. Just tried 1.3.0:

![image](https://user-images.githubusercontent.com/16073961/210880329-9a975adb-d1a8-4c59-b7e7-8485874d25dc.png)

**Comment by studiowebux** [comment]
Hello !

Thanks for your suggestion, 

here is a draft: 
<img width="471" alt="image" src="https://user-images.githubusercontent.com/37277136/211137164-31680aa6-b3c2-46ad-a21a-dcc854cac2d0.png">

When you click on the info button, it will collapse this section with extra information about the pipeline

Does it fit your use case ?

**Comment by maxeber** [comment]
That is awesome 👏! Thanks, and yeah definitely works! The commit link is great idea, will be able to directly jump on a PR, it will be handy for sure as we work on many repositories.
