### ISSUE TITLE
[Feature Request] See and/or Update the "Change Detection Options" Pipeline Option

### ISSUE THREAD

**Issue by maxeber** [yet-another-tool/1b2i1c#8]
I wonder if we add the option to:

1. See the **change detection options**
2. Update the **change detection options**

For this we might required to know which branch the pipeline is targeting
- https://github.com/yet-another-tool/1b2i1c/issues/7

![image](https://user-images.githubusercontent.com/16073961/210818044-6bb5f04a-fa3c-4fca-b609-69cf171afbcb.png)

**Comment by studiowebux** [comment]
PR Opened : https://github.com/yet-another-tool/1b2i1c/pull/10

**Comment by maxeber** [comment]
@studiowebux Would it be possible to allow updating the **changes detection** without having to trigger a the pipeline? Not sure if this is a priority but could offer a better UX and less unnecessary processing on our pipeline?

![image](https://user-images.githubusercontent.com/16073961/211351659-5d1e5b6d-ac08-43df-81f0-76a9c58d8bc2.png)

I would the the flow like
- pick pipeline
- enter branch name
- click "refresh" to get the **AWS CodePipeline Status**
- then you see the **Detect Changes:  {toggle button}** somewhere

**Comment by maxeber** [comment]
Awesome thanks!
